# Generated by Django 5.2.17 on 2026-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='statut',
            field=models.CharField(default='Brouillon'),
        ),
    ]
